# Generated by Django 4.2.6 on 2023-10-28 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, null=True, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=30, null=True, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=30, null=True, verbose_name='Email')),
                ('tipo_documento', models.CharField(choices=[('DNI', 'Documento Nacional de Identidad'), ('LC', 'Libreta Cívica'), ('LE', 'Libreta de Enrolamiento'), ('CI', 'Cédula de Identidad')], default='DNI', max_length=35, null=True, verbose_name='Tipo de documento')),
                ('numero_documento', models.CharField(max_length=11, null=True, verbose_name='Documento número')),
                ('firma', models.ImageField(blank=True, null=True, upload_to='firmas/', verbose_name='Firma')),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_presupuesto', models.IntegerField(verbose_name='Presupuesto')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('condicion_de_pago', models.CharField(max_length=250, verbose_name='Condición de pago')),
                ('validez', models.CharField(max_length=150, null=True, verbose_name='Validez')),
                ('plazo_de_entrega', models.CharField(max_length=250, null=True, verbose_name='Plazo de entrega')),
                ('tipo_de_cambio', models.CharField(max_length=250, verbose_name='Tipo de cambio')),
                ('observacion', models.CharField(max_length=250, verbose_name='Observación')),
                ('numero_operador', models.IntegerField(verbose_name='Operador')),
                ('estado_del_presupuesto', models.CharField(max_length=30, verbose_name='Estado del presupuesto')),
                ('contacto', models.CharField(max_length=150, verbose_name='Nombre del contacto')),
                ('fecha_dias_habiles', models.DateField(verbose_name='Fecha días hábiles')),
                ('total_neto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total neto')),
            ],
        ),
        migrations.CreateModel(
            name='Prospecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(default=0, max_length=30, verbose_name='Razón Social')),
                ('nombre_fantasia', models.CharField(default=0, max_length=30, verbose_name='Nombre de Fantasía')),
                ('estado', models.CharField(default=0, max_length=10, verbose_name='Estado')),
                ('cuit', models.CharField(default=0, max_length=13, verbose_name='CUIT')),
                ('numero_prospecto', models.IntegerField(default=0, verbose_name='Prospecto')),
                ('contactado', models.CharField(max_length=100, null=True, verbose_name='Contactado')),
                ('fecha_ultimo_contacto', models.DateField(null=True, verbose_name='Fecha de último contacto')),
                ('cliente', models.IntegerField(null=True, verbose_name='Cliente')),

            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(default=0, max_length=30, verbose_name='Razón Social')),
                ('nombre_fantasia', models.CharField(default=0, max_length=30, verbose_name='Nombre de Fantasía')),
                ('estado', models.CharField(default=0, max_length=10, verbose_name='Estado')),
                ('cuit', models.CharField(default=0, max_length=13, verbose_name='CUIT')),
                ('numero_proveedor', models.IntegerField(default=0, verbose_name='Proveedor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubro', models.CharField(default=0, max_length=255, verbose_name='Rubro')),
            ],
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.persona')),
                ('numero_operador', models.IntegerField(verbose_name='Operador')),
            ],
            bases=('core.persona',),
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30, verbose_name='Tipo de Teléfono')),
                ('numero_telefono', models.CharField(max_length=15, verbose_name='Número de Teléfono')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.persona')),
            ],
        ),
        migrations.CreateModel(
            name='SubRubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subrubro', models.CharField(default=0, max_length=255, verbose_name='Subrubro')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rubro')),
            ],
        ),
        migrations.CreateModel(
            name='Registracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de registracion')),
                ('numero_prospecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.prospecto')),
            ],
        ),
        migrations.CreateModel(
            name='PresupuestoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_de_producto', models.CharField(max_length=13, null=True, verbose_name='Código de producto')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('descripcion', models.CharField(max_length=250, null=True, verbose_name='Descripción del producto')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('moneda', models.CharField(choices=[('USD', 'u$s'), ('ARS', '$')], default='USD', max_length=3, verbose_name='Moneda')),
                ('tipo_de_unidad', models.CharField(choices=[('p/millar', 'millar'), ('p/unidad', 'unidad'), ('precio', 'precio')], default='p/millar', max_length=10, verbose_name='Tipo de unidad')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('proveedor_ppto', models.IntegerField(verbose_name='Provvedor ppto.')),
                ('fecha_ppto_proveedor', models.DateField(verbose_name='Fecha ppto.')),
                ('tipo_de_cambio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tipo de cbio ppto.')),
                ('presupuesto_numero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.presupuesto')),
            ],
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='cliente',
            field=models.ManyToManyField(to='core.prospecto'),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informacion_adicional', models.TextField(verbose_name='Información Adicional')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30, verbose_name='Tipo de Domicilio')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.persona')),
            ],
        ),
    ]
