# Generated by Django 4.2.6 on 2024-01-03 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operador',
            name='persona',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='operador_persona', to='core.persona'),
            preserve_default=False,
        ),
    ]
