# Generated by Django 4.2.6 on 2023-10-28 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospecto',
            name='rubro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.rubro'),
        ),
        migrations.AddField(
            model_name='prospecto',
            name='subrubro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.subrubro'),
        ),
    ]
