# Generated by Django 4.2.6 on 2024-01-08 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_operador_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='idcliente',
            field=models.IntegerField(null=True, verbose_name='IdCliente'),
        ),
    ]
